apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one-html
data:
  index.html: |
    <html><body style="font-family:sans-serif">
      <h1>App ONE</h1>
      <p>Ceci est la page personnalisee de app1.com</p>
    </body></html>
