apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-html
data:
  index.html: |
    <html><body style="font-family:sans-serif">
      <h1>App TWO </h1>
      <p>Bienvenue sur app2.com â€” page dediee.</p>
    </body></html>
