apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-html
data:
  index.html: |
    <html><body style="font-family:sans-serif">
      <h1>App THREE </h1>
      <p>App3.com â€” contenu personnalise.</p>
    </body></html>
